FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY package*.json ./
COPY prisma ./prisma/
COPY tsconfig.json ./
RUN npm ci
COPY src ./src
RUN npx prisma generate
CMD ["npx", "ts-node", "--project", "tsconfig.json", "src/jobs/worker.ts"]
