import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const MOCK_PRODUCTS = [
  {
    asin: 'B09B4MLLZ3',
    name: 'Oral-B Pro 1000 Electric Toothbrush Power Rechargeable',
    category: 'Health & Beauty',
    imageUrl: 'https://m.media-amazon.com/images/I/61evn2-BFKL._SL75_.jpg',
    upc: '069055856890',
    sourceUrl: 'https://www.walmart.com/ip/oral-b-pro-1000/654321',
    sourceRetailer: 'Walmart',
    sourcePrice: 29.99,
    finalCost: 23.21,
    estimatedResellPrice: 54.99,
    buyBoxPrice: 54.99,
    lowestListedPrice: 49.99,
    amazonUrl: 'https://www.amazon.com/dp/B09B4MLLZ3',
    amazonFees: 8.97,
    prepFee: 8.25,
    taxAmount: 8.25,
    netProfit: 14.31,
    roi: 61.7,
    bsr: 1842,
    bsrPercentage: 0.07,
    bsrTrend: 'TRENDING_UP',
    categoryRank: 3,
    categoryRankName: 'Electric Toothbrushes',
    seasonality: 'YEAR_ROUND',
    fbaSellers: 8,
    totalSellers: 14,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['Rakuten', 'BeFrugal'],
    keepaLink: 'https://keepa.com/#!product/1-B09B4MLLZ3',
    availableDiscounts: [
      { source: 'Rakuten', type: 'CASHBACK', amount: 4.50, percentage: 15 },
      { source: 'BeFrugal', type: 'CASHBACK', amount: 2.28, percentage: 7.6 },
    ],
  },
  {
    asin: 'B07FZ8S74R',
    name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker 6qt',
    category: 'Home & Kitchen',
    imageUrl: 'https://m.media-amazon.com/images/I/71V1-D35UCL._SL75_.jpg',
    upc: '810028581738',
    sourceUrl: 'https://www.target.com/p/instant-pot-duo/-/A-12345',
    sourceRetailer: 'Target',
    sourcePrice: 59.99,
    finalCost: 47.39,
    estimatedResellPrice: 99.99,
    buyBoxPrice: 99.99,
    lowestListedPrice: 94.99,
    amazonUrl: 'https://www.amazon.com/dp/B07FZ8S74R',
    amazonFees: 18.72,
    prepFee: 15.00,
    taxAmount: 15.00,
    netProfit: 18.88,
    roi: 39.8,
    bsr: 4201,
    bsrPercentage: 0.08,
    bsrTrend: 'STABLE',
    categoryRank: 8,
    categoryRankName: 'Electric Pressure Cookers',
    seasonality: 'PEAK_SEASON',
    fbaSellers: 11,
    totalSellers: 18,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['Capital One Shopping', 'Rakuten'],
    keepaLink: 'https://keepa.com/#!product/1-B07FZ8S74R',
    availableDiscounts: [
      { source: 'Capital One Shopping', type: 'CASHBACK', amount: 9.00, percentage: 15 },
      { source: 'Rakuten', type: 'CASHBACK', amount: 3.60, percentage: 6 },
    ],
  },
  {
    asin: 'B001TH7GUU',
    name: 'Stanley Classic Vacuum Insulated Wide Mouth Bottle 32oz',
    category: 'Sports & Outdoors',
    imageUrl: 'https://m.media-amazon.com/images/I/61CPt8WZFBL._SL75_.jpg',
    upc: '020337030152',
    sourceUrl: 'https://www.target.com/p/stanley-bottle/-/A-77001',
    sourceRetailer: 'Target',
    sourcePrice: 27.99,
    finalCost: 21.43,
    estimatedResellPrice: 49.99,
    buyBoxPrice: 49.99,
    lowestListedPrice: 46.99,
    amazonUrl: 'https://www.amazon.com/dp/B001TH7GUU',
    amazonFees: 10.47,
    prepFee: 7.50,
    taxAmount: 7.50,
    netProfit: 11.09,
    roi: 51.7,
    bsr: 2914,
    bsrPercentage: 0.12,
    bsrTrend: 'TRENDING_UP',
    categoryRank: 5,
    categoryRankName: 'Sports Water Bottles',
    seasonality: 'TRENDING',
    fbaSellers: 6,
    totalSellers: 10,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['Rakuten', 'TopCashback'],
    keepaLink: 'https://keepa.com/#!product/1-B001TH7GUU',
    availableDiscounts: [
      { source: 'Rakuten', type: 'CASHBACK', amount: 4.48, percentage: 16 },
      { source: 'TopCashback', type: 'CASHBACK', amount: 2.08, percentage: 7.4 },
    ],
  },
  {
    asin: 'B00A2KD8NY',
    name: 'Monopoly Classic Board Game Family Party Game',
    category: 'Toys & Games',
    imageUrl: 'https://m.media-amazon.com/images/I/81oet3ZYDAL._SL75_.jpg',
    upc: '630509575138',
    sourceUrl: 'https://www.walmart.com/ip/monopoly/987654',
    sourceRetailer: 'Walmart',
    sourcePrice: 14.99,
    finalCost: 11.09,
    estimatedResellPrice: 29.99,
    buyBoxPrice: 29.99,
    lowestListedPrice: 27.49,
    amazonUrl: 'https://www.amazon.com/dp/B00A2KD8NY',
    amazonFees: 5.72,
    prepFee: 4.50,
    taxAmount: 4.50,
    netProfit: 4.18,
    roi: 37.7,
    bsr: 8522,
    bsrPercentage: 0.50,
    bsrTrend: 'TRENDING_DOWN',
    categoryRank: 12,
    categoryRankName: 'Family Board Games',
    seasonality: 'PEAK_SEASON',
    fbaSellers: 9,
    totalSellers: 21,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['BeFrugal', 'RetailMeNot'],
    keepaLink: 'https://keepa.com/#!product/1-B00A2KD8NY',
    availableDiscounts: [
      { source: 'BeFrugal', type: 'CASHBACK', amount: 2.25, percentage: 15 },
      { source: 'RetailMeNot', type: 'COUPON', amount: 1.65, percentage: 11, code: 'SAVE11' },
    ],
  },
  {
    asin: 'B07HBQPZP9',
    name: 'Sharpie Permanent Markers Fine Point 24 Pack Assorted',
    category: 'Office Products',
    imageUrl: 'https://m.media-amazon.com/images/I/71rZG9WBxZL._SL75_.jpg',
    upc: '071641730244',
    sourceUrl: 'https://www.staples.com/sharpie-24pack/product_SS123',
    sourceRetailer: 'Staples',
    sourcePrice: 12.99,
    finalCost: 9.49,
    estimatedResellPrice: 24.99,
    buyBoxPrice: 24.99,
    lowestListedPrice: 22.99,
    amazonUrl: 'https://www.amazon.com/dp/B07HBQPZP9',
    amazonFees: 5.62,
    prepFee: 3.75,
    taxAmount: 3.75,
    netProfit: 2.38,
    roi: 25.1,
    bsr: 5122,
    bsrPercentage: 0.17,
    bsrTrend: 'STABLE',
    categoryRank: 2,
    categoryRankName: 'Permanent Markers',
    seasonality: 'YEAR_ROUND',
    fbaSellers: 12,
    totalSellers: 24,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['Capital One Shopping'],
    keepaLink: 'https://keepa.com/#!product/1-B07HBQPZP9',
    availableDiscounts: [
      { source: 'Capital One Shopping', type: 'CASHBACK', amount: 3.50, percentage: 12 },
    ],
  },
  {
    asin: 'B08BHXG144',
    name: 'BLACK+DECKER Hand Vacuum Cordless Pivot 20V Max',
    category: 'Home & Kitchen',
    imageUrl: 'https://m.media-amazon.com/images/I/71UYNrWHmOL._SL75_.jpg',
    upc: '050875776032',
    sourceUrl: 'https://www.homedepot.com/p/black-decker-vac/303412345',
    sourceRetailer: 'Home Depot',
    sourcePrice: 39.99,
    finalCost: 30.39,
    estimatedResellPrice: 69.99,
    buyBoxPrice: 69.99,
    lowestListedPrice: 64.99,
    amazonUrl: 'https://www.amazon.com/dp/B08BHXG144',
    amazonFees: 13.47,
    prepFee: 10.50,
    taxAmount: 10.50,
    netProfit: 15.13,
    roi: 49.8,
    bsr: 7344,
    bsrPercentage: 0.15,
    bsrTrend: 'TRENDING_UP',
    categoryRank: 6,
    categoryRankName: 'Cordless Hand Vacuums',
    seasonality: 'YEAR_ROUND',
    fbaSellers: 7,
    totalSellers: 13,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['Rakuten', 'BeFrugal'],
    keepaLink: 'https://keepa.com/#!product/1-B08BHXG144',
    availableDiscounts: [
      { source: 'Rakuten', type: 'CASHBACK', amount: 5.60, percentage: 14 },
      { source: 'BeFrugal', type: 'CASHBACK', amount: 4.00, percentage: 10 },
    ],
  },
  {
    asin: 'B07D4H5DJR',
    name: 'Tile Mate (2022) Bluetooth Tracker 4-Pack',
    category: 'Electronics',
    imageUrl: 'https://m.media-amazon.com/images/I/71+lCqQvHpL._SL75_.jpg',
    sourceUrl: 'https://www.target.com/p/tile-mate/-/A-52341',
    sourceRetailer: 'Target',
    sourcePrice: 64.99,
    finalCost: 51.34,
    estimatedResellPrice: 109.99,
    buyBoxPrice: 109.99,
    lowestListedPrice: 99.99,
    amazonUrl: 'https://www.amazon.com/dp/B07D4H5DJR',
    amazonFees: 13.20,
    prepFee: 16.50,
    taxAmount: 16.50,
    netProfit: 22.45,
    roi: 43.7,
    bsr: 12440,
    bsrPercentage: 0.38,
    bsrTrend: 'TRENDING_DOWN',
    categoryRank: 4,
    categoryRankName: 'Bluetooth Trackers',
    seasonality: 'PEAK_SEASON',
    fbaSellers: 5,
    totalSellers: 9,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['TopCashback', 'CardBear'],
    keepaLink: 'https://keepa.com/#!product/1-B07D4H5DJR',
    availableDiscounts: [
      { source: 'TopCashback', type: 'CASHBACK', amount: 9.10, percentage: 14 },
      { source: 'CardBear', type: 'REWARD', amount: 4.55, percentage: 7 },
    ],
  },
  {
    asin: 'B07NF76M5L',
    name: 'Cuisinart DCC-3200P1 Perfectemp Coffee Maker 14 Cup',
    category: 'Home & Kitchen',
    imageUrl: 'https://m.media-amazon.com/images/I/81R1F2JCQYL._SL75_.jpg',
    sourceUrl: 'https://www.kohls.com/product/cuisinart-coffee/12345.jsp',
    sourceRetailer: "Kohl's",
    sourcePrice: 49.99,
    finalCost: 37.99,
    estimatedResellPrice: 89.99,
    buyBoxPrice: 89.99,
    lowestListedPrice: 82.99,
    amazonUrl: 'https://www.amazon.com/dp/B07NF76M5L',
    amazonFees: 17.22,
    prepFee: 13.50,
    taxAmount: 13.50,
    netProfit: 17.78,
    roi: 46.8,
    bsr: 9001,
    bsrPercentage: 0.18,
    bsrTrend: 'STABLE',
    categoryRank: 11,
    categoryRankName: 'Drip Coffee Makers',
    seasonality: 'YEAR_ROUND',
    fbaSellers: 9,
    totalSellers: 16,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['Rakuten', 'RetailMeNot'],
    keepaLink: 'https://keepa.com/#!product/1-B07NF76M5L',
    availableDiscounts: [
      { source: 'Rakuten', type: 'CASHBACK', amount: 7.50, percentage: 15 },
      { source: 'RetailMeNot', type: 'COUPON', amount: 4.50, percentage: 9, code: 'KOHL9OFF' },
    ],
  },
];

async function main() {
  console.log('Seeding database...');

  // Create admin user
  const adminPassword = await bcrypt.hash(
    process.env.ADMIN_PASSWORD || 'Admin123!',
    12,
  );

  const admin = await prisma.user.upsert({
    where: { email: process.env.ADMIN_EMAIL || 'admin@arbitragepro.ai' },
    update: {},
    create: {
      email: process.env.ADMIN_EMAIL || 'admin@arbitragepro.ai',
      name: 'Admin',
      passwordHash: adminPassword,
      role: 'ADMIN',
      subscriptionPlan: 'ENTERPRISE',
    },
  });

  // Create demo user
  const demoPassword = await bcrypt.hash('Demo123!', 12);
  const demo = await prisma.user.upsert({
    where: { email: 'demo@arbitragepro.ai' },
    update: {},
    create: {
      email: 'demo@arbitragepro.ai',
      name: 'Demo User',
      passwordHash: demoPassword,
      role: 'USER',
      subscriptionPlan: 'PRO',
    },
  });

  // Create weekly batch
  const batch = await prisma.weeklyBatch.upsert({
    where: { weekNumber_year: { weekNumber: 1, year: 2025 } },
    update: {},
    create: {
      weekNumber: 1,
      year: 2025,
      status: 'COMPLETED',
      totalFound: MOCK_PRODUCTS.length,
      totalPassed: MOCK_PRODUCTS.length,
      completedAt: new Date(),
    },
  });

  // Create retailer sources
  const retailers = [
    { name: 'Target', baseUrl: 'https://www.target.com' },
    { name: 'Walmart', baseUrl: 'https://www.walmart.com' },
    { name: 'Best Buy', baseUrl: 'https://www.bestbuy.com' },
    { name: 'Home Depot', baseUrl: 'https://www.homedepot.com' },
    { name: "Kohl's", baseUrl: 'https://www.kohls.com' },
    { name: 'Staples', baseUrl: 'https://www.staples.com' },
    { name: 'Costco', baseUrl: 'https://www.costco.com' },
    { name: "Chewy", baseUrl: 'https://www.chewy.com' },
    { name: "Lowe's", baseUrl: 'https://www.lowes.com' },
    { name: "Macy's", baseUrl: 'https://www.macys.com' },
  ];

  for (const retailer of retailers) {
    await prisma.retailerSource.upsert({
      where: { name: retailer.name },
      update: {},
      create: retailer,
    });
  }

  // Seed products
  for (const product of MOCK_PRODUCTS) {
    await prisma.product.upsert({
      where: { asin: product.asin },
      update: {},
      create: {
        ...product,
        availableDiscounts: product.availableDiscounts,
        weeklyBatchId: batch.id,
        status: 'ACTIVE',
      },
    });
  }

  // Save a couple products for the demo user
  const products = await prisma.product.findMany({ take: 3 });
  for (const product of products) {
    await prisma.savedProduct.upsert({
      where: { userId_productId: { userId: demo.id, productId: product.id } },
      update: {},
      create: {
        userId: demo.id,
        productId: product.id,
        notes: 'Looks profitable, need to verify stock',
        tags: ['high-roi', 'watchlist'],
      },
    });
  }

  console.log(`✓ Admin: ${admin.email}`);
  console.log(`✓ Demo: demo@arbitragepro.ai / Demo123!`);
  console.log(`✓ ${MOCK_PRODUCTS.length} products seeded`);
  console.log(`✓ ${retailers.length} retailer sources added`);
  console.log('Seeding complete.');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
