import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const MOCK_PRODUCTS = [
  {
    asin: 'B09B4MLLZ3',
    name: 'Oral-B Pro 1000 Rechargeable Electric Toothbrush, Black',
    category: 'Health & Beauty',
    imageUrl: 'https://m.media-amazon.com/images/I/61evn2-BFKL._SL75_.jpg',
    upc: '069055856890',
    sourceUrl: 'https://www.walmart.com/search?q=Oral-B+Pro+1000+Electric+Toothbrush',
    sourceRetailer: 'Walmart',
    sourcePrice: 39.97,
    finalCost: 30.58,
    estimatedResellPrice: 54.97,
    buyBoxPrice: 54.97,
    lowestListedPrice: 49.99,
    amazonUrl: 'https://www.amazon.com/dp/B09B4MLLZ3',
    amazonFees: 8.97,
    prepFee: 7.50,
    taxAmount: 3.59,
    netProfit: 11.33,
    roi: 37.1,
    bsr: 1842,
    bsrPercentage: 0.07,
    bsrTrend: 'TRENDING_UP',
    categoryRank: 3,
    categoryRankName: 'Electric Toothbrushes',
    seasonality: 'YEAR_ROUND',
    fbaSellers: 8,
    totalSellers: 14,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['Rakuten', 'BeFrugal'],
    keepaLink: 'https://keepa.com/#!product/1-B09B4MLLZ3',
    availableDiscounts: [
      { source: 'Rakuten', type: 'CASHBACK', amount: 4.00, percentage: 10 },
      { source: 'BeFrugal', type: 'CASHBACK', amount: 2.00, percentage: 5 },
    ],
    hasBrandGating: false,
    hasCounterfeitRisk: false,
    isHazmat: false,
    isRestrictedCategory: false,
  },
  {
    asin: 'B07FZ8S74R',
    name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker, 6 Quart',
    category: 'Home & Kitchen',
    imageUrl: 'https://m.media-amazon.com/images/I/71V1-D35UCL._SL75_.jpg',
    upc: '810028581738',
    sourceUrl: 'https://www.target.com/s?searchTerm=Instant+Pot+Duo+7+in+1+6+quart',
    sourceRetailer: 'Target',
    sourcePrice: 59.99,
    finalCost: 47.39,
    estimatedResellPrice: 99.95,
    buyBoxPrice: 99.95,
    lowestListedPrice: 92.99,
    amazonUrl: 'https://www.amazon.com/dp/B07FZ8S74R',
    amazonFees: 18.72,
    prepFee: 14.25,
    taxAmount: 5.40,
    netProfit: 14.19,
    roi: 29.9,
    bsr: 4201,
    bsrPercentage: 0.08,
    bsrTrend: 'STABLE',
    categoryRank: 8,
    categoryRankName: 'Electric Pressure Cookers',
    seasonality: 'PEAK_SEASON',
    fbaSellers: 11,
    totalSellers: 18,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['Rakuten', 'Capital One Shopping'],
    keepaLink: 'https://keepa.com/#!product/1-B07FZ8S74R',
    availableDiscounts: [
      { source: 'Rakuten', type: 'CASHBACK', amount: 6.00, percentage: 10 },
      { source: 'Capital One Shopping', type: 'CASHBACK', amount: 3.00, percentage: 5 },
    ],
    hasBrandGating: false,
    hasCounterfeitRisk: false,
    isHazmat: false,
    isRestrictedCategory: false,
  },
  {
    asin: 'B00TTD9BRC',
    name: 'CeraVe Moisturizing Cream for Normal to Dry Skin, 19 oz',
    category: 'Health & Beauty',
    imageUrl: 'https://m.media-amazon.com/images/I/71OmPLePiJL._SL75_.jpg',
    upc: '301871574217',
    sourceUrl: 'https://www.walmart.com/search?q=CeraVe+Moisturizing+Cream+19+oz',
    sourceRetailer: 'Walmart',
    sourcePrice: 14.97,
    finalCost: 11.77,
    estimatedResellPrice: 24.99,
    buyBoxPrice: 24.99,
    lowestListedPrice: 22.49,
    amazonUrl: 'https://www.amazon.com/dp/B00TTD9BRC',
    amazonFees: 5.25,
    prepFee: 4.25,
    taxAmount: 1.35,
    netProfit: 5.37,
    roi: 45.6,
    bsr: 892,
    bsrPercentage: 0.03,
    bsrTrend: 'TRENDING_UP',
    categoryRank: 1,
    categoryRankName: 'Body Creams & Moisturizers',
    seasonality: 'YEAR_ROUND',
    fbaSellers: 6,
    totalSellers: 12,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['Ibotta', 'BeFrugal'],
    keepaLink: 'https://keepa.com/#!product/1-B00TTD9BRC',
    availableDiscounts: [
      { source: 'Ibotta', type: 'CASHBACK', amount: 2.00, percentage: 13.4 },
      { source: 'BeFrugal', type: 'CASHBACK', amount: 1.20, percentage: 8 },
    ],
    hasBrandGating: false,
    hasCounterfeitRisk: false,
    isHazmat: false,
    isRestrictedCategory: false,
  },
  {
    asin: 'B07NF76M5L',
    name: 'Cuisinart DCC-3200P1 Perfectemp Coffee Maker, 14 Cup Programmable',
    category: 'Home & Kitchen',
    imageUrl: 'https://m.media-amazon.com/images/I/81R1F2JCQYL._SL75_.jpg',
    upc: '086279186348',
    sourceUrl: 'https://www.kohls.com/search/results.do?keyword=Cuisinart+DCC-3200+coffee+maker',
    sourceRetailer: "Kohl's",
    sourcePrice: 49.99,
    finalCost: 38.49,
    estimatedResellPrice: 89.99,
    buyBoxPrice: 89.99,
    lowestListedPrice: 82.99,
    amazonUrl: 'https://www.amazon.com/dp/B07NF76M5L',
    amazonFees: 17.22,
    prepFee: 12.75,
    taxAmount: 4.50,
    netProfit: 17.03,
    roi: 44.2,
    bsr: 9001,
    bsrPercentage: 0.18,
    bsrTrend: 'STABLE',
    categoryRank: 11,
    categoryRankName: 'Drip Coffee Makers',
    seasonality: 'YEAR_ROUND',
    fbaSellers: 9,
    totalSellers: 16,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['Rakuten', 'RetailMeNot'],
    keepaLink: 'https://keepa.com/#!product/1-B07NF76M5L',
    availableDiscounts: [
      { source: 'Rakuten', type: 'CASHBACK', amount: 7.50, percentage: 15 },
      { source: 'RetailMeNot', type: 'COUPON', amount: 4.50, percentage: 9, code: 'KOHL15OFF' },
    ],
    hasBrandGating: false,
    hasCounterfeitRisk: false,
    isHazmat: false,
    isRestrictedCategory: false,
  },
  {
    asin: 'B00A2KD8NY',
    name: 'Hasbro Gaming Monopoly Classic Board Game',
    category: 'Toys & Games',
    imageUrl: 'https://m.media-amazon.com/images/I/81oet3ZYDAL._SL75_.jpg',
    upc: '630509575138',
    sourceUrl: 'https://www.walmart.com/search?q=Monopoly+Classic+Board+Game',
    sourceRetailer: 'Walmart',
    sourcePrice: 14.97,
    finalCost: 11.21,
    estimatedResellPrice: 29.97,
    buyBoxPrice: 29.97,
    lowestListedPrice: 26.99,
    amazonUrl: 'https://www.amazon.com/dp/B00A2KD8NY',
    amazonFees: 5.72,
    prepFee: 4.25,
    taxAmount: 1.35,
    netProfit: 7.44,
    roi: 66.4,
    bsr: 8522,
    bsrPercentage: 0.50,
    bsrTrend: 'TRENDING_UP',
    categoryRank: 12,
    categoryRankName: 'Family Board Games',
    seasonality: 'PEAK_SEASON',
    fbaSellers: 7,
    totalSellers: 15,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['BeFrugal', 'Ibotta'],
    keepaLink: 'https://keepa.com/#!product/1-B00A2KD8NY',
    availableDiscounts: [
      { source: 'BeFrugal', type: 'CASHBACK', amount: 1.50, percentage: 10 },
      { source: 'Ibotta', type: 'CASHBACK', amount: 1.00, percentage: 6.7 },
    ],
    hasBrandGating: false,
    hasCounterfeitRisk: false,
    isHazmat: false,
    isRestrictedCategory: false,
  },
  {
    asin: 'B07HBQPZP9',
    name: 'Sharpie Permanent Markers Fine Point, Assorted Colors, 24 Count',
    category: 'Office Products',
    imageUrl: 'https://m.media-amazon.com/images/I/71rZG9WBxZL._SL75_.jpg',
    upc: '071641730244',
    sourceUrl: 'https://www.staples.com/search?query=Sharpie+permanent+markers+24+pack',
    sourceRetailer: 'Staples',
    sourcePrice: 12.99,
    finalCost: 9.49,
    estimatedResellPrice: 23.99,
    buyBoxPrice: 23.99,
    lowestListedPrice: 21.49,
    amazonUrl: 'https://www.amazon.com/dp/B07HBQPZP9',
    amazonFees: 5.62,
    prepFee: 3.75,
    taxAmount: 1.17,
    netProfit: 3.96,
    roi: 41.7,
    bsr: 5122,
    bsrPercentage: 0.17,
    bsrTrend: 'STABLE',
    categoryRank: 2,
    categoryRankName: 'Permanent Markers',
    seasonality: 'YEAR_ROUND',
    fbaSellers: 10,
    totalSellers: 22,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['Capital One Shopping'],
    keepaLink: 'https://keepa.com/#!product/1-B07HBQPZP9',
    availableDiscounts: [
      { source: 'Capital One Shopping', type: 'CASHBACK', amount: 1.30, percentage: 10 },
    ],
    hasBrandGating: false,
    hasCounterfeitRisk: false,
    isHazmat: false,
    isRestrictedCategory: false,
  },
  {
    asin: 'B08BHXG144',
    name: 'BLACK+DECKER Dustbuster AdvancedClean Cordless Hand Vacuum, 20V',
    category: 'Home & Kitchen',
    imageUrl: 'https://m.media-amazon.com/images/I/71UYNrWHmOL._SL75_.jpg',
    upc: '050875776032',
    sourceUrl: 'https://www.homedepot.com/s/BLACK%2BDECKER+hand+vacuum+cordless',
    sourceRetailer: 'Home Depot',
    sourcePrice: 39.97,
    finalCost: 30.38,
    estimatedResellPrice: 69.99,
    buyBoxPrice: 69.99,
    lowestListedPrice: 64.97,
    amazonUrl: 'https://www.amazon.com/dp/B08BHXG144',
    amazonFees: 13.47,
    prepFee: 9.75,
    taxAmount: 3.60,
    netProfit: 12.79,
    roi: 42.1,
    bsr: 7344,
    bsrPercentage: 0.15,
    bsrTrend: 'TRENDING_UP',
    categoryRank: 6,
    categoryRankName: 'Cordless Hand Vacuums',
    seasonality: 'YEAR_ROUND',
    fbaSellers: 7,
    totalSellers: 13,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['Rakuten', 'BeFrugal'],
    keepaLink: 'https://keepa.com/#!product/1-B08BHXG144',
    availableDiscounts: [
      { source: 'Rakuten', type: 'CASHBACK', amount: 4.00, percentage: 10 },
      { source: 'BeFrugal', type: 'CASHBACK', amount: 2.00, percentage: 5 },
    ],
    hasBrandGating: false,
    hasCounterfeitRisk: false,
    isHazmat: false,
    isRestrictedCategory: false,
  },
  {
    asin: 'B082CRYZ3R',
    name: 'Sharpie S-Gel, Gel Pens, Fine Point (0.5mm), Black Ink, 4 Count',
    category: 'Office Products',
    imageUrl: 'https://m.media-amazon.com/images/I/71G1sMYajQL._SL75_.jpg',
    upc: '071641006609',
    sourceUrl: 'https://www.staples.com/search?query=Sharpie+S-Gel+gel+pens+fine+point',
    sourceRetailer: 'Staples',
    sourcePrice: 7.99,
    finalCost: 5.99,
    estimatedResellPrice: 14.99,
    buyBoxPrice: 14.99,
    lowestListedPrice: 12.97,
    amazonUrl: 'https://www.amazon.com/dp/B082CRYZ3R',
    amazonFees: 3.75,
    prepFee: 2.50,
    taxAmount: 0.72,
    netProfit: 2.03,
    roi: 33.9,
    bsr: 3210,
    bsrPercentage: 0.11,
    bsrTrend: 'TRENDING_UP',
    categoryRank: 4,
    categoryRankName: 'Gel Ink Rollerball Pens',
    seasonality: 'YEAR_ROUND',
    fbaSellers: 5,
    totalSellers: 9,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER' as const,
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW' as const,
    ipRiskReasons: [],
    discountSources: ['Capital One Shopping', 'Rakuten'],
    keepaLink: 'https://keepa.com/#!product/1-B082CRYZ3R',
    availableDiscounts: [
      { source: 'Capital One Shopping', type: 'CASHBACK', amount: 0.80, percentage: 10 },
      { source: 'Rakuten', type: 'CASHBACK', amount: 0.48, percentage: 6 },
    ],
    hasBrandGating: false,
    hasCounterfeitRisk: false,
    isHazmat: false,
    isRestrictedCategory: false,
  },
];

async function main() {
  console.log('Seeding database...');

  const adminPassword = await bcrypt.hash(
    process.env.ADMIN_PASSWORD || 'Admin123!',
    12,
  );

  const admin = await prisma.user.upsert({
    where: { email: process.env.ADMIN_EMAIL || 'admin@eallsource.com' },
    update: {},
    create: {
      email: process.env.ADMIN_EMAIL || 'admin@eallsource.com',
      name: 'Admin',
      passwordHash: adminPassword,
      role: 'ADMIN',
      subscriptionPlan: 'ENTERPRISE',
    },
  });

  const demoPassword = await bcrypt.hash('Demo123!', 12);
  const demo = await prisma.user.upsert({
    where: { email: 'demo@eallsource.com' },
    update: {},
    create: {
      email: 'demo@eallsource.com',
      name: 'Demo User',
      passwordHash: demoPassword,
      role: 'USER',
      subscriptionPlan: 'PRO',
    },
  });

  const batch = await prisma.weeklyBatch.upsert({
    where: { weekNumber_year: { weekNumber: 24, year: 2026 } },
    update: {},
    create: {
      weekNumber: 24,
      year: 2026,
      status: 'COMPLETED',
      totalFound: MOCK_PRODUCTS.length,
      totalPassed: MOCK_PRODUCTS.length,
      completedAt: new Date(),
    },
  });

  // Clear old products so stale rows (wrong URLs, replaced ASINs) don't linger
  await prisma.savedProduct.deleteMany({});
  await prisma.product.deleteMany({});

  const retailers = [
    { name: 'Target', baseUrl: 'https://www.target.com' },
    { name: 'Walmart', baseUrl: 'https://www.walmart.com' },
    { name: 'Best Buy', baseUrl: 'https://www.bestbuy.com' },
    { name: 'Home Depot', baseUrl: 'https://www.homedepot.com' },
    { name: "Kohl's", baseUrl: 'https://www.kohls.com' },
    { name: 'Staples', baseUrl: 'https://www.staples.com' },
    { name: 'Costco', baseUrl: 'https://www.costco.com' },
    { name: 'Chewy', baseUrl: 'https://www.chewy.com' },
    { name: "Lowe's", baseUrl: 'https://www.lowes.com' },
    { name: "Macy's", baseUrl: 'https://www.macys.com' },
  ];

  for (const retailer of retailers) {
    await prisma.retailerSource.upsert({
      where: { name: retailer.name },
      update: {},
      create: retailer,
    });
  }

  for (const product of MOCK_PRODUCTS) {
    await prisma.product.upsert({
      where: { asin: product.asin },
      update: {
        ...product,
        availableDiscounts: product.availableDiscounts,
        weeklyBatchId: batch.id,
        status: 'ACTIVE',
      },
      create: {
        ...product,
        availableDiscounts: product.availableDiscounts,
        weeklyBatchId: batch.id,
        status: 'ACTIVE',
      },
    });
  }

  const products = await prisma.product.findMany({ take: 3 });
  for (const product of products) {
    await prisma.savedProduct.upsert({
      where: { userId_productId: { userId: demo.id, productId: product.id } },
      update: {},
      create: {
        userId: demo.id,
        productId: product.id,
        notes: 'Verified stock available, good ROI window',
        tags: ['high-roi', 'watchlist'],
      },
    });
  }

  console.log(`✓ Admin: ${admin.email}`);
  console.log(`✓ Demo: demo@eallsource.com / Demo123!`);
  console.log(`✓ ${MOCK_PRODUCTS.length} products seeded`);
  console.log(`✓ ${retailers.length} retailer sources added`);
  console.log('Seeding complete.');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
