import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const MOCK_PRODUCTS = [
  {
    asin: 'B09B4MLLZ3',
    title: 'Oral-B Pro 1000 Rechargeable Electric Toothbrush, Black',
    upc: '069055855664',
    category: 'Health & Beauty',
    sourceUrl: 'https://www.walmart.com/ip/oral-b-pro-1000/654321',
    sourceRetailer: 'Walmart',
    sourcePrice: 29.99,
    availableDiscounts: [
      { source: 'Rakuten', type: 'cashback', amount: 3.00, percentage: 10.0 },
      { source: 'BeFrugal', type: 'cashback', amount: 1.50, percentage: 5.0 },
    ],
    discountSources: ['Rakuten', 'BeFrugal'],
    finalCost: 25.49,
    amazonUrl: 'https://www.amazon.com/dp/B09B4MLLZ3',
    buyBoxPrice: 54.97,
    lowestListedPrice: 52.99,
    estimatedResellPrice: 52.99,
    price: 52.99,
    amazonFees: 7.95,
    prepFee: 1.50,
    taxAmount: 2.10,
    fees: 11.55,
    profit: 15.95,
    roi: 62.6,
    bsr: 1234,
    bsrPercentage: 0.05,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER',
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW',
    keepaLink: 'https://keepa.com/#!product/1-B09B4MLLZ3',
    score: 78,
  },
  {
    asin: 'B07FZ8S74R',
    title: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker, 6 Quart',
    upc: '810028592765',
    category: 'Home & Kitchen',
    sourceUrl: 'https://www.walmart.com/ip/instant-pot-duo-6qt/12345',
    sourceRetailer: 'Walmart',
    sourcePrice: 49.99,
    availableDiscounts: [
      { source: 'Capital One Shopping', type: 'cashback', amount: 2.50, percentage: 5.0 },
      { source: 'RetailMeNot', type: 'coupon', amount: 5.00, code: 'SAVE5INSTANT' },
    ],
    discountSources: ['Capital One Shopping', 'RetailMeNot'],
    finalCost: 42.49,
    amazonUrl: 'https://www.amazon.com/dp/B07FZ8S74R',
    buyBoxPrice: 99.95,
    lowestListedPrice: 89.99,
    estimatedResellPrice: 89.99,
    price: 89.99,
    amazonFees: 18.50,
    prepFee: 2.00,
    taxAmount: 3.50,
    fees: 24.00,
    profit: 23.50,
    roi: 55.3,
    bsr: 3421,
    bsrPercentage: 0.10,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER',
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW',
    keepaLink: 'https://keepa.com/#!product/1-B07FZ8S74R',
    score: 72,
  },
  {
    asin: 'B00TTD9BRC',
    title: 'CeraVe Moisturizing Cream for Normal to Dry Skin, 19 oz',
    upc: '301871289914',
    category: 'Health & Beauty',
    sourceUrl: 'https://www.target.com/p/cerave-moisturizing-cream/-/A-13071836',
    sourceRetailer: 'Target',
    sourcePrice: 11.99,
    availableDiscounts: [
      { source: 'TopCashback', type: 'cashback', amount: 0.72, percentage: 6.0 },
      { source: 'RetailMeNot', type: 'coupon', amount: 1.00, code: 'CERAVE1' },
    ],
    discountSources: ['TopCashback', 'RetailMeNot'],
    finalCost: 10.27,
    amazonUrl: 'https://www.amazon.com/dp/B00TTD9BRC',
    buyBoxPrice: 24.99,
    lowestListedPrice: 22.49,
    estimatedResellPrice: 22.49,
    price: 22.49,
    amazonFees: 5.40,
    prepFee: 1.00,
    taxAmount: 0.84,
    fees: 7.24,
    profit: 4.98,
    roi: 48.5,
    bsr: 892,
    bsrPercentage: 0.03,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER',
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW',
    keepaLink: 'https://keepa.com/#!product/1-B00TTD9BRC',
    score: 65,
  },
  {
    asin: 'B07NF76M5L',
    title: 'Cuisinart DCC-3200P1 Perfectemp Coffee Maker, 14 Cup Programmable',
    upc: '086279117809',
    category: 'Home & Kitchen',
    sourceUrl: "https://www.kohls.com/product/cuisinart-coffee-maker/12345.jsp",
    sourceRetailer: "Kohl's",
    sourcePrice: 39.99,
    availableDiscounts: [
      { source: 'Rakuten', type: 'cashback', amount: 2.00, percentage: 5.0 },
      { source: 'CardBear', type: 'rewards', amount: 5.00 },
    ],
    discountSources: ['Rakuten', 'CardBear'],
    finalCost: 32.99,
    amazonUrl: 'https://www.amazon.com/dp/B07NF76M5L',
    buyBoxPrice: 89.99,
    lowestListedPrice: 79.99,
    estimatedResellPrice: 79.99,
    price: 79.99,
    amazonFees: 16.00,
    prepFee: 2.00,
    taxAmount: 2.80,
    fees: 20.80,
    profit: 26.20,
    roi: 79.4,
    bsr: 5678,
    bsrPercentage: 0.11,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER',
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW',
    keepaLink: 'https://keepa.com/#!product/1-B07NF76M5L',
    score: 82,
  },
  {
    asin: 'B00A2KD8NY',
    title: 'Hasbro Gaming Monopoly Classic Board Game',
    upc: '653569376781',
    category: 'Toys & Games',
    sourceUrl: 'https://www.walmart.com/ip/monopoly-classic/987654',
    sourceRetailer: 'Walmart',
    sourcePrice: 12.99,
    availableDiscounts: [
      { source: 'BeFrugal', type: 'cashback', amount: 0.39, percentage: 3.0 },
      { source: 'Rakuten', type: 'cashback', amount: 0.65, percentage: 5.0 },
    ],
    discountSources: ['BeFrugal', 'Rakuten'],
    finalCost: 11.95,
    amazonUrl: 'https://www.amazon.com/dp/B00A2KD8NY',
    buyBoxPrice: 29.97,
    lowestListedPrice: 26.99,
    estimatedResellPrice: 26.99,
    price: 26.99,
    amazonFees: 8.50,
    prepFee: 1.00,
    taxAmount: 0.91,
    fees: 10.41,
    profit: 4.63,
    roi: 38.7,
    bsr: 12450,
    bsrPercentage: 0.73,
    autoUngated: true,
    buyBoxOwner: 'AMAZON',
    amazonIsSeller: true,
    amazonOwnsBuyBox: true,
    ipRiskScore: 'LOW',
    keepaLink: 'https://keepa.com/#!product/1-B00A2KD8NY',
    score: 52,
  },
  {
    asin: 'B07HBQPZP9',
    title: 'Sharpie Permanent Markers Fine Point, Assorted Colors, 24 Count',
    upc: '071641200411',
    category: 'Office Products',
    sourceUrl: 'https://www.staples.com/sharpie-24pk/product_SS123',
    sourceRetailer: 'Staples',
    sourcePrice: 9.97,
    availableDiscounts: [
      { source: 'RetailMeNot', type: 'coupon', amount: 1.00, code: 'STAPLES10' },
      { source: 'TopCashback', type: 'cashback', amount: 0.50, percentage: 5.0 },
    ],
    discountSources: ['RetailMeNot', 'TopCashback'],
    finalCost: 8.47,
    amazonUrl: 'https://www.amazon.com/dp/B07HBQPZP9',
    buyBoxPrice: 23.99,
    lowestListedPrice: 20.49,
    estimatedResellPrice: 20.49,
    price: 20.49,
    amazonFees: 5.40,
    prepFee: 1.00,
    taxAmount: 0.70,
    fees: 7.10,
    profit: 4.92,
    roi: 58.1,
    bsr: 8234,
    bsrPercentage: 0.27,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER',
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW',
    keepaLink: 'https://keepa.com/#!product/1-B07HBQPZP9',
    score: 68,
  },
  {
    asin: 'B08BHXG144',
    title: 'BLACK+DECKER Dustbuster AdvancedClean Cordless Hand Vacuum, 20V',
    upc: '885911750738',
    category: 'Home & Kitchen',
    sourceUrl: 'https://www.homedepot.com/p/black-decker-vac/303412345',
    sourceRetailer: 'Home Depot',
    sourcePrice: 29.99,
    availableDiscounts: [
      { source: 'Capital One Shopping', type: 'cashback', amount: 0.60, percentage: 2.0 },
      { source: 'RetailMeNot', type: 'coupon', amount: 2.00, code: 'HD2OFF' },
    ],
    discountSources: ['Capital One Shopping', 'RetailMeNot'],
    finalCost: 27.39,
    amazonUrl: 'https://www.amazon.com/dp/B08BHXG144',
    buyBoxPrice: 69.99,
    lowestListedPrice: 62.99,
    estimatedResellPrice: 62.99,
    price: 62.99,
    amazonFees: 13.75,
    prepFee: 2.50,
    taxAmount: 2.10,
    fees: 18.35,
    profit: 17.25,
    roi: 63.0,
    bsr: 7891,
    bsrPercentage: 0.16,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER',
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW',
    keepaLink: 'https://keepa.com/#!product/1-B08BHXG144',
    score: 74,
  },
  {
    asin: 'B082CRYZ3R',
    title: 'Sharpie S-Gel Pens Fine Point (0.5mm), Black Ink, 4 Count',
    upc: '071641956867',
    category: 'Office Products',
    sourceUrl: 'https://www.staples.com/sharpie-sgel-4pk/product_SS456',
    sourceRetailer: 'Staples',
    sourcePrice: 6.49,
    availableDiscounts: [
      { source: 'Rakuten', type: 'cashback', amount: 0.65, percentage: 10.0 },
    ],
    discountSources: ['Rakuten'],
    finalCost: 5.84,
    amazonUrl: 'https://www.amazon.com/dp/B082CRYZ3R',
    buyBoxPrice: 16.99,
    lowestListedPrice: 15.49,
    estimatedResellPrice: 15.49,
    price: 15.49,
    amazonFees: 3.87,
    prepFee: 1.00,
    taxAmount: 0.45,
    fees: 5.32,
    profit: 4.33,
    roi: 74.1,
    bsr: 19872,
    bsrPercentage: 0.66,
    autoUngated: true,
    buyBoxOwner: 'FBA_SELLER',
    amazonIsSeller: false,
    amazonOwnsBuyBox: false,
    ipRiskScore: 'LOW',
    keepaLink: 'https://keepa.com/#!product/1-B082CRYZ3R',
    score: 61,
  },
];

async function main() {
  console.log('Seeding database...');

  const adminPw = await bcrypt.hash(process.env.ADMIN_PASSWORD ?? 'Admin123!', 12);
  const demoPw  = await bcrypt.hash('Demo123!', 12);

  await prisma.user.upsert({
    where:  { email: process.env.ADMIN_EMAIL ?? 'admin@eallsource.com' },
    update: {},
    create: { email: process.env.ADMIN_EMAIL ?? 'admin@eallsource.com', password: adminPw },
  });

  await prisma.user.upsert({
    where:  { email: 'demo@eallsource.com' },
    update: {},
    create: { email: 'demo@eallsource.com', password: demoPw },
  });

  await prisma.user.upsert({
    where:  { email: 'savingdailystore@gmail.com' },
    update: {},
    create: { email: 'savingdailystore@gmail.com', password: await bcrypt.hash('EALLsource@Admin1', 12) },
  });

  await prisma.lead.deleteMany({});
  await prisma.product.deleteMany({});

  for (const p of MOCK_PRODUCTS) {
    const product = await prisma.product.create({ data: p });
    await prisma.lead.create({
      data: { productId: product.id, score: p.score, status: 'NEW' },
    });
  }

  console.log(`✓ ${process.env.ADMIN_EMAIL ?? 'admin@eallsource.com'} / ${process.env.ADMIN_PASSWORD ?? 'Admin123!'}`);
  console.log('✓ demo@eallsource.com / Demo123!');
  console.log('✓ savingdailystore@gmail.com / EALLsource@Admin1');
  console.log(`✓ ${MOCK_PRODUCTS.length} products + leads seeded`);
  console.log('Seeding complete.');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
